### ISSUE TITLE
Duplication of configuration parameters on hard disk?

### ISSUE THREAD

**Issue by greensquirrel** [STAR-PORT/aotpy#3]
Dear aotpy developers,

from the code example in the README.md, I have got the impression
that an aotpy.AOSystem object represents a single telemetry snapshot.  For instance,
the telemetry data of one AO loop cycle are included in one object
of type aotpy.AOSystem.  Please correct me if I am wrong!

Often some configuration parameters such as the control matrix are huge. 
In that case,  it makes sense to store them only once on hard disk.  
From the code example in the README,  I don't understand the concept to save
the telemetry data of serveral AO loop cycles without duplicating
configuration parameters on hard disk, i.e. the way to have only one control matrix 
on disk for several AO loop cycles.
In which way it is possible to avoid saving configuration parameters such as the control matrix on disk several times?  Can you give a code example maybe?

**Comment by kYwzor** [comment]
Hello @greensquirrel. Yes, an `aotpy.AOSystem` object represents a single telemetry snapshot, you have the right understanding.

The documentation definitely needs some work, but it is possible to store such files only once. Here's a quick example just for demonstration:
```python
import aotpy
import numpy as np
from astropy.io import fits

# Here we create a file to be shared between multiple AOSystem objects
# If the file already existed we could just use that instead
filename = 'example_matrix.fits'
example_matrix = np.ones((100, 100))
fits.writeto(filename, example_matrix)

# Here we are creating an aotpy.Image object that provides a reference to an external FITS file
# The reference is done via a path to the object
# (filename is enough in this case, since we are in the same directory)
external_image = aotpy.FITSFileImage(filename)

# Here we create two AOSystem objects, where the telescope's pupil mask is defined by the external FITS file
sys1 = aotpy.AOSystem(ao_mode='SCAO')
sys1.main_telescope = aotpy.MainTelescope('Example Telescope 1', pupil_mask=external_image)
sys1.write_to_file('test1.fits')

sys2 = aotpy.AOSystem(ao_mode='SCAO')
sys2.main_telescope = aotpy.MainTelescope('Example Telescope 2', pupil_mask=external_image)
sys2.write_to_file('test2.fits')
```
You can open "test1.fits" or "test2.fits" (with e.g. Astropy) and you will notice that they not contain any ImageHDU (nor the image data itself in any other way). With aotpy, you can open the files and image data like any other AOT file:
```python
import aotpy

sys1 = aotpy.read_system_from_fits('test1.fits')
sys2 = aotpy.read_system_from_fits('test2.fits')
```

And if we analyse the pupil mask data:
```python
print(sys1.main_telescope.pupil_mask == sys2.main_telescope.pupil_mask)
print(sys1.main_telescope.pupil_mask.data.shape)
print(sys1.main_telescope.pupil_mask)
```

we get
```python
True
(100, 100)
FITSFileImage(name='PRIMARY', data=array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype='>f8'), unit=None, time=None, metadata=[])
```
So we are able to get back the image data even though it is not stored in the AOT file itself.

Just a couple more notes here:

* This works because a reference to the file is saved in the AOT file, in this case `'FILEREF<example_matrix.fits>'`
* If you write a reference to a file not in the same directory it will still work (that is, if you had `filename = 'examplefolder/example_matrix.fits'` it would be ok). However, this would still be saved on the AOT file as `'FILEREF<example_matrix.fits>'`. When reading back, aotpy will attempt to find the referenced file in the same directory but, if it cannot find it, it will request the user to point to the relevant file via the file browser.

Hope this cleared up your question!

**Comment by greensquirrel** [comment]
Thank you for the example!  It makes sense! :-)

>     * If you write a reference to a file not in the same directory it will still work (that is, if you had `filename = 'examplefolder/example_matrix.fits'` it would be ok). However, this would still be saved on the AOT file as `'FILEREF<example_matrix.fits>'`. When reading back, aotpy will attempt to find the referenced file in the same directory but, if it cannot find it, it will request the user to point to the relevant file via the file browser.

Nice idea with the file browser :-)

I will close the ticket.
